version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9412
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9412:9412
    networks:
      - minial-api-net

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2019!"
      MSSQL_USER: "sa"
      ACCEPT_EULA: "1"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - minial-api-net

  flyway-structure:
    image: flyway/flyway
    depends_on:
      - sqlserver
    networks:
      - minial-api-net
    environment:
      - FLYWAY_EDITION=community
    command: -url="jdbc:sqlserver://sqlserver:1433;DatabaseName=master;encrypt=true;trustServerCertificate=true;" -user=sa -mixed=true -password=SqlServer2019! -connectRetries=10 migrate
    volumes:
      - ../migrations/structure_sql_scripts:/flyway/sql/

  flyway-data:
    image: flyway/flyway
    depends_on:
      - sqlserver
      - flyway-structure
    networks:
      - minial-api-net
    environment:
      - FLYWAY_EDITION=community
    command: -url="jdbc:sqlserver://sqlserver:1433;DatabaseName=master;encrypt=true;trustServerCertificate=true;" -user=sa -mixed=true -password=SqlServer2019! -connectRetries=10 migrate
    volumes:
      - ../migrations/data_sql_scripts:/flyway/sql/
  
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ../terraform/localhost:/infra
    working_dir: /infra
    networks:
      - minial-api-net
       
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./grafana:/mnt/config
    networks:
      - minial-api-net

  promtail:
    image: grafana/promtail:2.6.1
    depends_on:
      - loki
    volumes:
      - ./grafana:/mnt/config
      - ./logs:/var/log
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - minial-api-net

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
      - grafana-config:/etc/grafana
    ports:
      - "3000:3000"
    networks:
      - minial-api-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - minial-api-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55670:55679"
      - "8889:8889"
      - "8888:8888"
    depends_on:
      - jaeger
      - prometheus      
    networks:
      - minial-api-net
        
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - minial-api-net
        
  redis:
    image: 'ubuntu/redis:latest'
    environment:
      - REDIS_PASSWORD=redisadmin123
      - REDIS_AOF_ENABLED=no
      - TZ=UTC
    ports:
      - 6379:6379
    networks:
      - minial-api-net      

networks:
  minial-api-net:
    driver: bridge

volumes:
  mssql-data:
    driver: local
  grafana-data:
    driver: local
  grafana-logs:
    driver: local
  grafana-config:
    driver: local
  prometheus-data:
    driver: local
